# Generated by Django 3.1.7 on 2021-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp1', models.CharField(max_length=5, null=True)),
                ('temp2', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
