# Generated by Django 3.1.7 on 2021-06-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('telegram_user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_class', models.CharField(default='not important', max_length=15)),
                ('bed', models.CharField(max_length=5, null=True)),
                ('baby', models.CharField(max_length=5, null=True)),
                ('pet', models.CharField(max_length=5, null=True)),
                ('breakfast', models.CharField(max_length=5, null=True)),
                ('fullName', models.CharField(default=None, max_length=50, null=True)),
                ('phone', models.CharField(default=None, max_length=15, null=True)),
                ('email', models.CharField(default=None, max_length=50, null=True)),
                ('is_firm', models.SmallIntegerField(default=None, null=True)),
                ('country', models.CharField(default=None, max_length=20, null=True)),
                ('start_date', models.DateTimeField(default=None, null=True)),
                ('finish_date', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
