# Generated by Django 3.1.7 on 2021-03-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='temp3',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='temp4',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
