# Generated by Django 3.1.7 on 2021-03-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210318_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='userTelegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.CharField(max_length=10)),
                ('bed', models.CharField(max_length=5, null=True)),
                ('baby', models.CharField(max_length=5, null=True)),
                ('pet', models.CharField(max_length=5, null=True)),
                ('breakfast', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
