# Generated by Django 3.1.7 on 2021-03-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210326_0637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': False},
        ),
    ]
