# Generated by Django 3.1.7 on 2021-05-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz', models.TextField()),
                ('en', models.TextField()),
                ('ru', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='usertelegram',
            name='lan',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
