# Generated by Django 3.1.7 on 2021-05-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210522_0510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
