# Generated by Django 3.1.7 on 2021-06-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usertelegram'),
        ),
    ]
